module: Solana

theme: fullwidth

custom_categories:
  - name: General Types
    children:
    - Byte
    - Base58
    - RPC
  - name: Making RPC Requests
    children:
    - RPCSession
    - RPCNode
    - RPCRequest
    - TaggedRPCRequest
    - RPCRequestAdaptor
  - name: Building and Sending Transactions
    children:
    - Transaction
	- TransactionInstruction
	- RawTransactionInstruction
    - CompilableInstructionSet
	- InstructionListBuilder
	- TransactionKey
  - name: JSON-RPC Requests
    children:
    - RPCRequestKeyedBody
    - RPCRequestPayload
  - name: JSON-RPC Responses
    children:
    - RPCResponse
    - RPCResponseAndContext
    - RPCResponseContext
    - TaggedRPCResponse
    - NodeHealthResponse
    - GetInflationRewardResult
    - GetLargestAccountsResult
    - LamportBalanceStatement
  - name: Writing New Request/Response Code
    children:
    - NoKeyedBody
  - name: System Extensions
    children:
    - String
