type_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  min_length: 
    error: 1
    excluded:
      - id
      - url
line_length:
  warning: 150
  ignores_comments: true
disabled_rules:
- nesting
- identifier_name
- shorthand_operator