name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nathanlawrence/setup-swift
      with:
          swift-version: '99.0'
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Print version
      run: swift --version
